version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: plz_webapp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: plzapp
      POSTGRES_USER: plzuser
      POSTGRES_PASSWORD: plzpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: